<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.8.3.111 SP?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File>README.txt</File>
    <File Private="true">testSuite.var</File>
    <File>testSuite.c</File>
    <File>autoGeneratedFile.c</File>
    <File Description="Variables used in testSet_AssertsExt" Private="true">varAssertExt.var</File>
    <File Description="Uses Assertions of Library utAssertExt">testSet_AssertsExt.c</File>
  </Files>
</Program>